### ISSUE TITLE
Consider integrating babel-plugin-typecheck

### ISSUE THREAD

**Issue by yrashk** [reactuate/reactuate#12]
https://github.com/codemix/babel-plugin-typecheck

**Comment by inxilpro** [comment]
Does this mean you're moving from tcomb to Flow? Or do you plan on using both?  If you're still going to use tcomb, would https://github.com/gcanti/babel-plugin-tcomb be a better fit?

**Comment by yrashk** [comment]
Not moving to flow, just thinking about supporting different options.

**Comment by yrashk** [comment]
By the way, I saw that plugin, but it is for babel5, we're on babel6
