### ISSUE TITLE
Domain building alternative

### ISSUE THREAD

**Issue by micimize** [reactuate/reactuate#15]
I've been experimenting with a more declarative domain creation syntax:

``` es6
export default BuildDomain({
    name: 'categories',
    types: {Category, Categories},
    dataFlows: [
        {
            action: {
                type: 'INSERT_CATEGORY',
                payload: t.maybe(Category)
            },
            reducer: {
                initialState: initialState,
                cases: [
                    (state, action) => {
                        if (Category.is(action.payload)){
                            return Categories.update({$push: action.payload});
                        }
                        return Categories
                    }
                ]
            }
        }
    ]
})
```

parsed by:

``` es6
function addDataFlowToDomain(domain, {
    action: {type, payload},
    reducer: {initialState={}, cases=[]}
}){
    let action = createAction(domain, type, payload)
    let reducer = createReducer(domain, initialState, action, ...cases)
}

export function BuildDomain({name, types={}, dataFlows=[]}){
    const domain = new Domain(name)
    dataFlows.map(dataFlow => addDataFlowToDomain(domain, dataFlow))
    domain.types = types
    return domain
}
```

Would this make sense to add to `reactuate`? It could also have alternative syntaxes for the dataFlow building - I'm not sure if my current syntax loses reducer flexibility

**Comment by yrashk** [comment]
Thanks for opening this issue! What was your primary motivation behind this type of syntax?

**Comment by micimize** [comment]
I think it has a few advantages:
1. Domains are declared, rather than built imperatively, allowing for a kind of DSL for domains
2. The entire overview of a domain is kept in one place
3. The structure is consistent and predictable, allowing for potential further meta programming of Domains, such as automated refactoring

**Comment by yrashk** [comment]
The way I see it right now, the current approach is not far off from that. Sure, it looks rather imperative the way you write, but all those functions modify the domain object which becomes the declaration which can be read by other tools and even manipulated if necessary.

Besides, I suspect that the purely declarative approach would lose some composability (won't be easy to wrap action creators into other action creators if necessary), it makes using tcomb's `match` API impossible as there are no declared tcomb action creator types to match against.

Thoughts?

**Comment by micimize** [comment]
I'm not sure I understand the `match` limitation, but I can see what you mean about loss of composability. 
I think having the domain distilled as a data structure representing it's orchestration is pretty beneficial for code clarity, but it may be better for me to make the solution more robust as a separate module first.

**Comment by yrashk** [comment]
Yeah, it's definitely possible to make it a separate module and see how it works, to get a better feel. I am curious to see what can be accomplished! My initial Domain implementation is just a quick-n-dirty one as I needed to encapsulate all those things together.
