### ISSUE TITLE
different domains can't have the the same actions

### ISSUE THREAD

**Issue by micimize** [reactuate/reactuate#18]
in `createReducer.js`, `action.meta.name` (set by `domainMiddlewar.js`) is the unprefixed action name. This means that

``` es6
      let actionCreator = domain.get('actions')[domain.withoutPrefix(action.meta.name)]
      if (!t.Nil.is(actionCreator)) { ...
```

results in the reducer for `domainA/insert` attempting to handle `domainB/insert` actions, which will result in a tcomb `TypeError`.

My current patch is

``` es6
      let actionCreator = domain.get('actions')[domain.withoutPrefix(action.payload.type)]
      if (!t.Nil.is(actionCreator)) {
```

but maybe `action.meta.name` should be prefixed by the domain middleware.

**Comment by yrashk** [comment]
Sorry for taking so long to get back to you on this. I think you are right and `action.meta.name` should be prefixed. Do you mind preparing a PR?

**Comment by micimize** [comment]
sure - how are the program files generated from the `README.md`?

**Comment by yrashk** [comment]
`make`

On Thursday, 3 March 2016, Michael Joseph Rosenthal <
notifications@github.com> wrote:

> sure - how are the program files generated from the README.md?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reactuate/reactuate/issues/18#issuecomment-191845254.

## 

Y.
