### ISSUE TITLE
Hot reloading of `store` no longer automatic in react-redux 2.0

### ISSUE THREAD

**Issue by inxilpro** [reactuate/reactuate#21]
See: https://github.com/reactjs/react-redux/releases/tag/v2.0.0

This means that createStore will likely have to be changed. I'll see if I can submit a pull request, but I'm not 100% sure how to implement the change yet, so if anyone else has thoughts, that'd be helpful.

**Comment by cryptoquick** [comment]
Um, v2.0.0 released about six months ago. The project is at v4.4.0 now. You sure this is still relevant?

**Comment by inxilpro** [comment]
Yep, the change happened in 2.0 but still applies. It just means that Redux wants you to explicitly set up hot reloading of reducers.  Reactuate doesn't do this by default, so if you change your reducer, you have to reload your app.

I still haven't had a chance to play with this. I think it may be non-trivial to get hot reloading of reducers working in a way that is in line with reactuate's simplicity/zero-config setup.

**Comment by cryptoquick** [comment]
Ah, interesting. I did notice that earlier, actually, but didn't think much of it. Good call, this should definitely be addressed.

**Comment by inxilpro** [comment]
I'm actually not sure if this is possible the way reactuate works. Because the modules that are changing happen outside of reactuate, the best we may be able to do is provide a method on `Application` that lets you update the domains, and then provide documentation on how to implement hot reloading.

At the least we would need `Application.replaceDomain` which would swap out a domain definition and then re-create the reducers/store. Then you could do something like:

``` js
if (module.hot) {
  module.hot.accept('./domain', () => {
    const replacement = require('./domain');
    application.replaceDomain(replacement);
  });
}
```

`replaceDomain` could use `Array.filter` to remove the domain from the current array (by name) and then push the new one on and re-run most of the code in the `Application` constructor.

@yrashk Thoughts?

**Comment by yrashk** [comment]
I've started thinking on this some time ago, but haven't had time to come to any conclusion as of yet. My general line of thinking is that this type of functionality should work automatically for reactuate uses by default (and exposing some kind of mechanism for complex scenarios). Not sure how to accomplish this just yet.

**Comment by yrashk** [comment]
(But I am definitely open to suggestions and PRs). Right now I just reload pages with changed stores, but this is definitely suboptimal.
