### ISSUE TITLE
Question: how to initialize router with custom history ?

### ISSUE THREAD

**Issue by FranckErnewein** [reactuate/reactuate#32]
Hi,
In documentation I read

> We also standardize route initialization. This step is hidden from the end user.

But in my case, in production, my application run in a subdirectory (ex: `http://website.com/my-reactuate-app/` ) 
So I need create by myself history in order to define a `basename`

``` js
import { createHistory, useBasename } from 'history'

const history = useBasename(createHistory)({
  basename: '/my-reactuate-app'
})
```

I would like to know if it's possible to override the default `history` ?

**Comment by yrashk** [comment]
Hi Franck,

Sorry for the delay answering your question. There is currently no way to override the default. Do you want to send a patch? I will gladly accept one!

**Comment by lilobase** [comment]
Hello I work with @FranckErnewein on the project,

Do you prefer a config injection through environment variable (with envify) or by passing a config hash to the Application constructor ?

**Comment by yrashk** [comment]
Hi @lilobase, thanks for joining the effort! I personally side with the Application constructor route.

**Comment by lilobase** [comment]
I don't get what is the "Application constructor route" ?

**Comment by yrashk** [comment]
I meant your option of "passing a config hash to the Application constructor"

**Comment by FranckErnewein** [comment]
fixed by https://github.com/reactuate/reactuate/pull/33

you can now call Application constructor with a `basename` option:

``` js
const app = new Application({
  /* ... options ... */ 
  basename: '/my-reactuate-app'
});
```
