### ISSUE TITLE
Readme is very heavy on implementation details

### ISSUE THREAD

**Issue by joshduck** [reactuate/reactuate#8]
The objectives in the Readme piqued my interest, but I was disappointed to see that the rest of the Readme is mostly just code dumps of the helper functions. 

This isn't particularly helpful; if I knew enough about the components for this to be meaningful then I probably would have already built something like this myself. And, of course, if I'm really interested in the details I'd prefer to just explore the codebase. 

I'd love to see a run through of the TODO list mentioned in the Getting Started section.

**Comment by yrashk** [comment]
Josh,

Reactuate is in fact written as a _literate program_ to maintain the flow and reasoning behind the choices, relation to required packages, and other things together. Some parts of the code that don't present much value to the reader are hidden away from Markdown viewers within comments. 

That said, it's still a fairly new project and I know the README is not as perfect as I would have wanted it to be. Feel free to contribute if you can. I will be improving it on my end on an ongoing basis to make sure it's articulated better. The project was born out of my own frustration with the difficulties presented by the abundance of React-related software.

In the meantime, the best way to experience the stack is to try installing it in your new app, looking at the sample, etc.

**Comment by joshduck** [comment]
Thanks for the explanation. I hadn't heard of a README being used as the source of truth before. I hadn't installed and run it because I first came across the project on a mobile device :) That will probably be common with a Hacker News audience.
