### ISSUE TITLE
Proposal: using tcomb-react in the view layer

### ISSUE THREAD

**Issue by gcanti** [reactuate/reactuate#9]
Since you are using `tcomb` in the domain layer, [tcomb-react](https://github.com/gcanti/tcomb-react) would be handy in order to re-utilize your domain models as prop types:

``` js
import React from 'react'
import user from '../user' // domain
import { props, t } from 'tcomb-react'

@props({
  user: user.User,
  message: t.String
})
class Message extends React.Component {

  render() {
    return (
      <div> 
        <p><label>Email</label> {this.props.user.email}</p>
        <p><label>Message</label> {this.props.message}</p>
      </div>
    )
  }

}
```

**Comment by yrashk** [comment]
I think it's a good idea! :+1: And the good part is that even if there's a reason to not use tcomb-react for some specific cases, it is not an either or choice. One can always resort to the classic React approach for this.

**Comment by yrashk** [comment]
One minor concern: when I connect parts of the state to my components, I don't always include some reducer's State. Often, if my focus is narrower, I go for a specific part of it. With `comb-react` I'd have to either copy/paste the type of a particular property (if state is a struct) or extract it into a domain property altogether, which doesn't help keeping it concise. Would have been great if it was possible to have some sort of introspection into a `struct` type to select one of its property types. Thoughts?

**Comment by yrashk** [comment]
Thought this would be a really easy addition, but with react-redux, a little bit of extra work will be required:

```
Warning: Failed propType: [tcomb] Invalid additional prop(s):

[
  "history",
  "location",
  "params",
  "route",
  "routeParams",
  "routes",
  "children",
  "actions"
]

supplied to HomePage. Check the render method of `Connect(HomePage)`.
```

**Comment by yrashk** [comment]
I've started my work on this on https://github.com/reactuate/reactuate/tree/tcomb-react and I'll see what I can do about the above extra props.

**Comment by gcanti** [comment]
> Would have been great if it was possible to have some sort of introspection into a struct type to select one of its property types

In order to keep my domain model DRY I use a few techniques, I think you'll be interested in the 3rd one:

**1. Granular types**

``` js
// domain/Email.js
import t from 'tcomb'

export default t.refinement(t.String, (s) => /@/.test(s), 'Email')

...

// domain/UnidentifiedUser.js
import t from 'tcomb'
import Email from './Email'

export default t.struct({
  email: Email
}, 'UnidentifiedUser')
```

**2. Adding fields to a struct**

Using [mixins](https://github.com/gcanti/tcomb/blob/master/docs/API.md#extending-a-struct)

``` js
// domain/User.js
import UnidentifiedUser from './UnidentifiedUser'

// every field of TemporaryUser plus an id
export default UnidentifiedUser.extends({ id: t.String }, 'User')
```

**3. Narrowing down the type and/or automatically sync using runtime type introspection**

All `tcomb`'s types are introspectables at runtime (see the `meta` object in the [docs](https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-struct-combinator))

``` js
// domain/Message.js
import User from './User'

export default t.struct({
  email: User.meta.props.email, // automatically synced
  message: t.String
}, 'Message')
```

**Comment by gcanti** [comment]
> Thought this would be a really easy addition, but with react-redux...

Mhhh, I don't use `react-redux` (usually I inject a single prop containing an abstraction of the app) but I do use `react-router` so for top level components (and only for them) I relax the checks:

``` js
import { props } from 'tcomb-react'
import App from './App'

@props({
  app: App
}, { strict: false }) // <= relax
class TopLevelComponent extends React.Component {

}
```

**Comment by yrashk** [comment]
You were right, I do like the 3rd technique :) https://github.com/reactuate/reactuate/commit/9cb0f728f64ac95ce1e8c440370cb4b938527981

I am not so sure about relaxing the top level prop injection. I mean, understand it, but it adds some complexity. I don't really want every page component to have a special option attached to its props/propTypes. Trying to find the best way to handle this. Besides, in my code, I have components that are not top-level but are still `connect()`-ed to avoid passing the state through. Does this mean I'd have to override props/propTypes to always supply `strict: true` unless overriden? Not perfect either. I'll keep looking for a perfect solution.
